#!/bin/bash
rm results
echo "Dielectric           Density(g/L)           Temperature(K)           kappa(m^3/j)" >> results

for((i=0;i<11;i++));do

echo "0" | gmx dipoles -f prd-t$i.xtc -s prd-t$i.tpr >> cal4   # epsilon
echo "9 0" | gmx energy -f prd-t$i.edr -s prd-t$i.tpr >> cal1
echo "16 0" | gmx energy -f prd-t$i.edr -s prd-t$i.tpr >> cal2
echo "9 15 0" | gmx energy -f prd-t$i.edr -s prd-t$i.tpr -fluct_props >> cal3 # isothermal compressibility

file1="cal1"
first_value=$(grep "Temperature" "$file1" | awk '{print $2}')
t=$first_value

file2="cal2"
value=$(grep "Density" "$file2" | awk '{print $2}')
d=$value

file3="cal3"
kappa=$(grep "Isothermal Compressibility" "$file3" | awk '{print $(NF-1)}')
k=$kappa


file4="cal4"
last_line1=$(grep -oE '[0-9.]+' "$file4" | tail -n 1)
e=$last_line1



echo "$e           $d           $t           $k" >> results
echo "" >> results
rm cal*
done




