#!/bin/bash
mkdir TestParticleInsertion
cd TestParticleInsertion
for((i=0;i<11;i++));do
	mkdir TPI-t$i
done

cd ..

for((i=0;i<11;i++));do
	echo "3 0" | gmx trjconv -f prd-t$i.xtc -s prd-t$i.tpr -pbc mol -b 0 -n index.ndx -o out-t$i.gro
	mv out-t$i.gro TestParticleInsertion/TPI-t$i
	cp job.sh TPI.py config TestParticleInsertion/TPI-t$i

	cd TestParticleInsertion/TPI-t$i
	vim -c ":e config" -c ":%s/T=298.15/T=$(echo "scale=2; (($i*10))+270" | bc)/g" -c ":wq"
	vim -c ":e job.sh" -c ":%s/#SBATCH --job-name=T                                # Job Name/#SBATCH --job-name=T$i                                # Job Name/g" -c ":wq"
	mv job.sh job-t$i.sh
	cd ../../
done

	
cd TestParticleInsertion
for((i=0;i<11;i++));do

	cd TPI-t$i
	mv out-t$i.gro out.gro
	cd ..

done



